### ISSUE TITLE
Do you accept contributions of other ORMs?

### ISSUE THREAD

**Issue by Jaxelr** [InfoTechBridge/OrmBenchmark#1]
Is there some sort of requirement of allowable ORMs?

**Comment by AArayeshi** [comment]
Hi Jaxelr, sorry for my late. I saw your message now. I was very busy on other staffs.
There is no any requirement. It is open for other ORMs.

**Comment by Jaxelr** [comment]
Thanks for taking of your time to reply. :+1:
